networks:
  net:
    driver: bridge

services:
  database:
    image: postgres:latest
    container_name: database
    environment:
      POSTGRES_USER: alvarium
      POSTGRES_PASSWORD: 1234
    networks:
      - net

  mosquitto-server:
    image: eclipse-mosquitto:latest
    container_name: mosquitto-server
    volumes:
      - "../config:/mosquitto/config/"
    networks:
      - net

#  mosquitto-client:
#    image: mosquitto-client
#    container_name: mosquitto-client
#    depends_on:
#      - mosquitto-server
#    networks:
#      - net


#  worker:
#    depends_on:
#      - mosquitto-server
#    image: alvarium-worker:latest
#    container_name: alvarium-workers
#    networks:
#      - net

  bench:
    depends_on:
      - mosquitto-server
    image: alvarium-benchmark:latest
    container_name: master
    networks:
      - net
    ports:
      - 8849:8849
    volumes:
      - "~/jprofiler14:/jprofiler/"
      - "../data:/alvarium/data/"

