apiVersion: v1
kind: Service
metadata:
  name: alvarium-workers

spec:
  type: LoadBalancer
  selector:
    name: worker
  ports:
    - protocol: TCP
      port: 8080
      name: http
    - protocol: TCP
      port: 5540
      name: tls

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: alvarium-workers-tpm


spec:
  replicas: 2
  selector:
    matchLabels:
      name: worker


  template:
    metadata:
      labels:
        name: worker
    spec:
      containers:
        - name: alvarium-worker
          image: alvarium-worker
          imagePullPolicy: Never
          securityContext:
            privileged: true
          ports:
            - containerPort: 8080
            - containerPort: 5540
          volumeMounts:
            - mountPath: "/dev/tpm0"
              name: tpm-device

      volumes:
        - name: tpm-device
          hostPath:
            path: /dev/tpm0

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alvarium-workers-no-tpm


spec:
  replicas: 2
  selector:
    matchLabels:
      name: worker

  template:
    metadata:
      labels:
        name: worker
    spec:
      containers:
        - name: alvarium-worker
          image: alvarium-worker
          imagePullPolicy: Never
          securityContext:
            privileged: true
          ports:
            - containerPort: 8080
            - containerPort: 5540

---

apiVersion: v1
kind: Service
metadata:
  name: mosquitto-server

spec:
  selector:
    name: mosquitto-server
  clusterIP: None
  ports:
    - port: 1883
---

apiVersion: v1
kind: Pod
metadata:
  name: mosquitto-server
  labels:
    name: mosquitto-server
spec:
  containers:
    - name: mosquitto-server
      image: eclipse-mosquitto:latest
      volumeMounts:
        - mountPath: "/mosquitto/config/"
          name: mosquitto-conf

      ports:
        - containerPort: 1883

  volumes:
    - name: mosquitto-conf
      hostPath:
        type: Directory
        path: "/config/"
---
#
#apiVersion: v1
#kind: Pod
#metadata:
#  name: mosquitto-client
#
#spec:
#  containers:
#    - name: moquitto-client
#      image: mosquitto-client:latest
#      imagePullPolicy: IfNotPresent

---

apiVersion: v1
kind: Service
metadata:
  name: database

spec:
  clusterIP: None
  selector:
    name: database
  ports:
    - port: 5432

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: database-data-volume
  labels:
    type: local
spec:
  storageClassName: hostpath
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /database
  persistentVolumeReclaimPolicy: Delete
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-data-storage-claim
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: Pod
metadata:
  name: database
  labels:
    name: database
spec:
  securityContext:
    runAsUser: 1000
  containers:
    - name: database
      image: postgres:latest
      env:
        - name: POSTGRES_USER
          value: alvarium
        - name: POSTGRES_PASSWORD
          value: "1234"
      ports:
        - containerPort: 5432
      volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: database-data
  volumes:
    - name: database-data
      persistentVolumeClaim:
        claimName: database-data-storage-claim

---
apiVersion: v1
kind: Pod
metadata:
  name: master

spec:
  restartPolicy: Never
  containers:
    - name: master
      image: alvarium-master:latest
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - mountPath: "/alvarium/data"
          name: data
        - mountPath: "/dev/tpm0"
          name: tpm-device
          readOnly: false
      securityContext:
        privileged: true

  initContainers:
    - name: db-init
      image: db-init:latest
      imagePullPolicy: IfNotPresent

  volumes:
    - name: data
      hostPath:
        type: Directory
        path: "/ML-data"
    - name: tpm-device
      hostPath:
        path: /dev/tpm0
