
apiVersion: v1
kind: Service
metadata:
  name: alvarium-workers-service

spec:
  type: LoadBalancer
  selector:
    app: alvarium
  ports:
    - protocol: TCP
      port: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: alvarium-workers

spec:
  replicas: 3
  selector:
    matchLabels:
      app: alvarium
  template:
    metadata:
      labels:
        app: alvarium
    spec:
      containers:
        - name: alvarium-worker
          image: alvarium-worker
          imagePullPolicy: Never
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Pod
metadata:
  name: mosquitto
spec:
  containers:
    - name: mosquitto
      image: eclipse-mosquitto:latest
      volumeMounts:
        - mountPath: "/config/mosquitto.conf:/mosquitto/config/mosquitto.conf"
          name: mosquitto-conf

      ports:
        - containerPort: 1882

  volumes:
    - name: mosquitto-conf
      hostPath:
        path: "/config/mosquitto.conf"
---

apiVersion: v1
kind: Service
metadata:
  name: database-service

spec:
  clusterIP: None
  selector:
    name: database


---
apiVersion: v1
kind: Pod
metadata:
  name: database
  labels:
    name: database
spec:
  containers:
    - name: database
      image: postgres
      ports:
        - containerPort: 5432

---
apiVersion: v1
kind: Pod
metadata:
  name: master
spec:
  containers:
    - name: master
      image: alvarium-master
      imagePullPolicy: Never
      volumeMounts:
        - mountPath: "/alvarium/data"
          name: data
  volumes:
    - name: data
      hostPath:
        path: "/ML-data"

