apiVersion: v1
kind: Service
metadata:
  name: alvarium-workers

spec:
  type: LoadBalancer
  selector:
    name: worker
  ports:
    - protocol: TCP
      port: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: alvarium-workers


spec:
  replicas: 2
  selector:
    matchLabels:
      name: worker

  template:
    metadata:
      labels:
        name: worker
    spec:
      containers:
        - name: alvarium-worker
          image: alvarium-worker
          imagePullPolicy: Never
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: mosquitto-server

spec:
  selector:
    name: mosquitto-server
  clusterIP: None
  ports:
    - port: 1883
---

apiVersion: v1
kind: Pod
metadata:
  name: mosquitto-server
  labels:
    name: mosquitto-server
spec:
  containers:
    - name: mosquitto-server
      image: eclipse-mosquitto:latest
      volumeMounts:
        - mountPath: "/mosquitto/config/"
          name: mosquitto-conf

      ports:
        - containerPort: 1883

  volumes:
    - name: mosquitto-conf
      hostPath:
        type: Directory
        path: "/config/"
---

apiVersion: v1
kind: Pod
metadata:
  name: mosquitto-client

spec:
  containers:
    - name: moquitto-client
      image: mosquitto-client:latest
      imagePullPolicy: IfNotPresent

---

apiVersion: v1
kind: Service
metadata:
  name: database

spec:
  clusterIP: None
  selector:
    name: database
  ports:
    - port: 5432
---

apiVersion: v1
kind: Pod
metadata:
  name: database
  labels:
    name: database
spec:
  containers:
    - name: database
      image: postgres:latest
      env:
        - name: POSTGRES_USER
          value: alvarium
        - name: POSTGRES_PASSWORD
          value: "1234"
      ports:
        - containerPort: 5432

---
apiVersion: v1
kind: Pod
metadata:
  name: master
spec:
  restartPolicy: OnFailure
  containers:
    - name: master
      image: alvarium-master:latest
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - mountPath: "/alvarium/data"
          name: data

  initContainers:
    - name: db-init
      image: db-init:latest
      imagePullPolicy: IfNotPresent

  volumes:
    - name: data
      hostPath:
        type: Directory
        path: "/ML-data"

